version: 2
jobs:
  build:
    working_directory: ~/example-go-circle
    docker:
      - image: codequest/ruby-golang-java-nodejs

    steps:
      - checkout            
      - run:
          name: install-go
          command: |
            go list -m all
