version: 2
jobs:
  build:
    docker:
      - image: lfirek/golang-java

    steps:
      - checkout            
      - run:
          name: install-go
          command: |
            go build go.mod
