version: 2
jobs:
  build:
    working_directory: ~/example-go-circle
    docker:
      - image: jonathell/multi-manager
    environment:
      GO111MODULE: "on"
    steps:
      - checkout            
      - run:
          name: install-go
          command: |
            go version
            go mod download
            bash <(curl -s https://scripts.scantist.com/staging/ci-circle.sh)
        
