version: 2
jobs:
  build:
    docker:
      - image: timbru31/java-node

    steps:
      - checkout            
      - run:
          name: install-go
          command: |
            go build
            go list
