version: 2
jobs:
  build:
    docker:
      - image: jonathell/java-golang
      
    steps:
      - checkout            
      - run:
          name: install-go
          command: |
            go version
            go mod download 
            bash <(curl -s https://scripts.scantist.com/ci-circle.sh)
        
