version: 2
jobs:
  build:
    working_directory: ~/example-go-circle
    docker:
      - image: lfirek/golang-java

    steps:
      - checkout            
      - run:
          name: install-go
          command: |
            ls
