version: 2
jobs:
  build:
    working_directory: ~/example-go-circle
    docker:
      - image: circleci/golang:1.12
    environment:
      GO111MODULE: "on"
    steps:
      - checkout            
      - run:
          name: install-go
          command: |
            go version
            go mod download
